import type { Service, ServicePack } from "./types";

export const services: Service[] = [
  {
    id: "conseil-standard",
    title: "Séance stratégique (standard)",
    description: "Échange personnalisé pour comprendre votre projet, répondre à vos questions et vous orienter efficacement avant votre arrivée en RDC.",
    shortDescription: "Échange personnalisé pour comprendre votre projet et vous orienter.",
    category: "Conseil Avant Départ",
    relevantFor: ["court-sejour", "installation", "investissement", "exploration", "expat"],
  },
  {
    id: "conseil-premium",
    title: "Séance stratégique (premium)",
    description: "Analyse approfondie pour profils exigeants (investisseurs, expatriés, projets complexes) avec recommandations concrètes et plan d'action.",
    shortDescription: "Analyse approfondie avec recommandations et plan d'action.",
    category: "Conseil Avant Départ",
    relevantFor: ["installation", "investissement", "expat"],
  },
  {
    id: "audit-projet",
    title: "Audit projet diaspora",
    description: "Étude complète de votre projet (retour ou investissement) avec identification des risques, opportunités et stratégie d'implantation.",
    shortDescription: "Étude complète avec identification des risques et opportunités.",
    category: "Conseil Avant Départ",
    relevantFor: ["installation", "investissement"],
  },
  {
    id: "conseil-expat-premium",
    title: "Conseil expatriation premium",
    description: "Accompagnement complet pour préparer votre expatriation : formalités, logistique, intégration culturelle et conseils pratiques.",
    shortDescription: "Accompagnement complet pour préparer votre expatriation.",
    category: "Conseil Avant Départ",
    relevantFor: ["expat"],
  },
  {
    id: "assistance-permis-travail",
    title: "Assistance permis de travail",
    description: "Accompagnement complet pour l'obtention de votre permis de travail et documents professionnels.",
    shortDescription: "Obtention de votre permis de travail et documents.",
    category: "Formalisation Expatrié",
    relevantFor: ["expat"],
  },
  {
    id: "assistance-visa-expat",
    title: "Assistance visa expatrié",
    description: "Gestion complète de vos démarches de visa d'expatriation et renouvellement.",
    shortDescription: "Gestion de vos démarches de visa et renouvellement.",
    category: "Formalisation Expatrié",
    relevantFor: ["expat"],
  },
  {
    id: "pack-documents-expat",
    title: "Pack documents expatrié",
    description: "Formalisation complète de tous vos documents administratifs (permis, visa, attestations).",
    shortDescription: "Formalisation de tous vos documents administratifs.",
    category: "Formalisation Expatrié",
    relevantFor: ["expat"],
  },
  {
    id: "accueil-simple",
    title: "Accueil aéroport simple",
    description: "Un agent vous accueille à l'aéroport pour faciliter vos premières démarches et vous orienter dès votre arrivée.",
    shortDescription: "Agent d'accueil à l'aéroport pour vous orienter.",
    category: "Arrivée & Mobilité",
    subcategory: "Accueil & Coordination",
    relevantFor: ["court-sejour", "installation", "investissement", "exploration", "expat", "retraite"],
  },
  {
    id: "chauffeur-simple",
    title: "Chauffeur sécurisé (aller simple)",
    description: "Transfert sécurisé de l'aéroport vers votre logement avec chauffeur sélectionné et fiable.",
    shortDescription: "Transfert sécurisé de l'aéroport vers votre logement.",
    category: "Arrivée & Mobilité",
    subcategory: "Accueil & Coordination",
    relevantFor: ["court-sejour", "installation", "investissement", "exploration", "expat", "retraite"],
  },
  {
    id: "assistance-complete",
    title: "Assistance complète arrivée",
    description: "Prise en charge globale : accueil, gestion bagages, transport et premières recommandations terrain.",
    shortDescription: "Prise en charge globale dès votre arrivée.",
    category: "Arrivée & Mobilité",
    subcategory: "Accueil & Coordination",
    relevantFor: ["court-sejour", "installation", "investissement", "expat", "retraite"],
  },
  {
    id: "chauffeur-ar",
    title: "Chauffeur aller/retour",
    description: "Transport sécurisé aller-retour pour vos déplacements essentiels.",
    shortDescription: "Transport sécurisé pour vos déplacements.",
    category: "Arrivée & Mobilité",
    subcategory: "Accueil & Coordination",
    relevantFor: ["court-sejour", "installation", "investissement", "expat", "retraite"],
  },
  {
    id: "assistance-48h",
    title: "Assistance 48h",
    description: "Accompagnement intensif pendant vos premières 48h pour éviter erreurs, pertes de temps et mauvaises décisions.",
    shortDescription: "Accompagnement intensif pendant vos premières 48h.",
    category: "Arrivée & Mobilité",
    subcategory: "Accueil & Coordination",
    relevantFor: ["installation", "investissement", "expat", "retraite"],
  },
  {
    id: "accueil-vip",
    title: "Accueil VIP protocolaire",
    description: "Expérience premium avec accueil prioritaire, coordination avancée et service haut de gamme.",
    shortDescription: "Expérience premium avec accueil prioritaire.",
    category: "Arrivée & Mobilité",
    subcategory: "Accueil & Coordination",
    relevantFor: ["investissement"],
  },
  {
    id: "chauffeur-journee",
    title: "Chauffeur dédié (journée)",
    description: "Mise à disposition d'un chauffeur sécurisé pendant 8h pour vos déplacements en toute tranquillité.",
    shortDescription: "Chauffeur sécurisé à disposition pendant 8h.",
    category: "Arrivée & Mobilité",
    subcategory: "Accueil & Coordination",
    relevantFor: ["court-sejour", "investissement"],
  },
  {
    id: "reservation-billet",
    title: "Réservation billet avion",
    description: "Gestion et optimisation de vos billets avec nos partenaires pour garantir sécurité et fiabilité.",
    shortDescription: "Gestion et optimisation de vos billets d'avion.",
    category: "Arrivée & Mobilité",
    subcategory: "Mobilité & Voyage",
    relevantFor: ["court-sejour", "installation", "investissement", "exploration"],
  },
  {
    id: "organisation-sejour",
    title: "Organisation séjour",
    description: "Planification complète de votre séjour (hébergement, transport, agenda) selon vos objectifs.",
    shortDescription: "Planification complète de votre séjour.",
    category: "Arrivée & Mobilité",
    subcategory: "Mobilité & Voyage",
    relevantFor: ["court-sejour", "exploration"],
  },
  {
    id: "recherche-logement",
    title: "Recherche logement",
    description: "Sélection de logements fiables, visites organisées et négociation sécurisée avec propriétaires.",
    shortDescription: "Sélection et visites de logements fiables.",
    category: "Installation & Vie",
    subcategory: "Logement",
    relevantFor: ["installation", "expat", "retraite"],
  },
  {
    id: "visite-accompagnee",
    title: "Visite accompagnée",
    description: "Accompagnement sur le terrain pour visiter et évaluer plusieurs logements.",
    shortDescription: "Accompagnement pour visiter et évaluer des logements.",
    category: "Installation & Vie",
    subcategory: "Logement",
    relevantFor: ["installation", "expat", "retraite"],
  },
  {
    id: "verification-logement",
    title: "Vérification logement",
    description: "Audit du logement (sécurité, conformité, environnement).",
    shortDescription: "Audit du logement pour sécurité et conformité.",
    category: "Installation & Vie",
    subcategory: "Logement",
    relevantFor: ["installation", "expat", "retraite"],
  },
  {
    id: "assistance-signature",
    title: "Assistance signature contrat",
    description: "Vérification et sécurisation du contrat de location.",
    shortDescription: "Vérification et sécurisation de votre contrat.",
    category: "Installation & Vie",
    subcategory: "Logement",
    relevantFor: ["installation", "investissement", "expat"],
  },
  {
    id: "mise-service-utilites",
    title: "Mise en service utilités",
    description: "Activation eau, électricité, internet et autres services essentiels.",
    shortDescription: "Activation de vos services essentiels.",
    category: "Installation & Vie",
    subcategory: "Installation",
    relevantFor: ["installation", "expat", "retraite"],
  },
  {
    id: "coordination-installation",
    title: "Coordination installation",
    description: "Organisation globale de votre installation (prestataires, équipements, suivi).",
    shortDescription: "Organisation globale de votre installation.",
    category: "Installation & Vie",
    subcategory: "Installation",
    relevantFor: ["installation", "expat", "retraite"],
  },
  {
    id: "installation-premium",
    title: "Installation premium complète",
    description: "Prise en charge totale pour une installation clé en main sans stress.",
    shortDescription: "Installation clé en main sans stress.",
    category: "Installation & Vie",
    subcategory: "Installation",
    relevantFor: ["installation", "investissement", "expat", "retraite"],
  },
  {
    id: "orientation-terrain",
    title: "Journée orientation terrain",
    description: "Découverte guidée des quartiers, services essentiels et bonnes pratiques locales.",
    shortDescription: "Découverte guidée des quartiers et services.",
    category: "Installation & Vie",
    subcategory: "Orientation Quotidienne",
    relevantFor: ["installation", "exploration", "expat"],
  },
  {
    id: "orientation-medicale",
    title: "Orientation médicale",
    description: "Mise en relation avec des structures de santé fiables et adaptées.",
    shortDescription: "Mise en relation avec des structures de santé.",
    category: "Santé & Assistance",
    relevantFor: ["installation", "investissement", "expat"],
  },
  {
    id: "accompagnement-clinique",
    title: "Accompagnement clinique",
    description: "Présence et assistance lors de vos consultations médicales.",
    shortDescription: "Assistance lors de vos consultations médicales.",
    category: "Santé & Assistance",
    relevantFor: ["installation", "investissement", "expat", "retraite"],
  },
  {
    id: "assistance-hospitaliere",
    title: "Assistance hospitalière",
    description: "Coordination complète en cas d'hospitalisation.",
    shortDescription: "Coordination en cas d'hospitalisation.",
    category: "Santé & Assistance",
    relevantFor: ["installation", "investissement", "expat", "retraite"],
  },
  {
    id: "ouverture-compte",
    title: "Ouverture compte bancaire",
    description: "Accompagnement complet pour ouvrir un compte sécurisé et adapté à votre profil.",
    shortDescription: "Ouverture d'un compte bancaire sécurisé.",
    category: "Banque & Assurance",
    subcategory: "Banque",
    relevantFor: ["installation", "investissement", "expat", "retraite"],
  },
  {
    id: "assistance-bancaire",
    title: "Assistance dossier bancaire",
    description: "Préparation et optimisation de votre dossier.",
    shortDescription: "Préparation de votre dossier bancaire.",
    category: "Banque & Assurance",
    subcategory: "Banque",
    relevantFor: ["installation", "investissement", "expat", "retraite"],
  },
  {
    id: "accompagnement-rdv-banque",
    title: "Accompagnement rendez-vous",
    description: "Présence et assistance lors de votre rendez-vous bancaire.",
    shortDescription: "Assistance lors de votre rendez-vous bancaire.",
    category: "Banque & Assurance",
    subcategory: "Banque",
    relevantFor: ["installation", "investissement", "expat", "retraite"],
  },
  {
    id: "creation-entreprise-simple",
    title: "Création entreprise simple",
    description: "Mise en place rapide d'une structure légale.",
    shortDescription: "Mise en place rapide d'une structure légale.",
    category: "Formalisation & Régularisation",
    relevantFor: ["investissement"],
  },
  {
    id: "creation-entreprise-complete",
    title: "Création entreprise complète",
    description: "Accompagnement global jusqu'à l'opérationnalité.",
    shortDescription: "Accompagnement global jusqu'à l'opérationnalité.",
    category: "Formalisation & Régularisation",
    relevantFor: ["investissement"],
  },
  {
    id: "assistance-rccm",
    title: "Assistance RCCM",
    description: "Gestion des démarches administratives d'enregistrement.",
    shortDescription: "Gestion des démarches d'enregistrement RCCM.",
    category: "Formalisation & Régularisation",
    relevantFor: ["investissement"],
  },
  {
    id: "conformite-fiscale",
    title: "Mise en conformité fiscale",
    description: "Organisation et régularisation de votre situation fiscale.",
    shortDescription: "Régularisation de votre situation fiscale.",
    category: "Formalisation & Régularisation",
    relevantFor: ["investissement"],
  },
  {
    id: "diagnostic-projet",
    title: "Diagnostic projet",
    description: "Analyse rapide pour valider la pertinence de votre projet.",
    shortDescription: "Analyse rapide de la pertinence de votre projet.",
    category: "Business & Investissement",
    relevantFor: ["investissement"],
  },
  {
    id: "etude-faisabilite",
    title: "Étude de faisabilité",
    description: "Analyse approfondie du marché, des risques et des opportunités.",
    shortDescription: "Analyse du marché et des opportunités.",
    category: "Business & Investissement",
    relevantFor: ["investissement"],
  },
  {
    id: "mise-relation-partenaires",
    title: "Mise en relation partenaires",
    description: "Connexion avec des acteurs fiables et stratégiques.",
    shortDescription: "Connexion avec des acteurs stratégiques.",
    category: "Business & Investissement",
    relevantFor: ["investissement"],
  },
  {
    id: "accompagnement-strategique",
    title: "Accompagnement stratégique",
    description: "Suivi personnalisé pour structurer et développer votre projet.",
    shortDescription: "Suivi pour structurer et développer votre projet.",
    category: "Business & Investissement",
    relevantFor: ["investissement"],
  },
  {
    id: "coaching-individuel-nextgen",
    title: "Coaching individuel",
    description: "Accompagnement pour orientation et développement personnel adapté aux jeunes.",
    shortDescription: "Accompagnement pour orientation et développement.",
    category: "Bridge Next-Gen",
    relevantFor: ["nextgen", "study", "business", "employment"],
  },
  {
    id: "programme-mentorat-nextgen",
    title: "Programme mentorat",
    description: "Accès à un réseau de mentors expérimentés pour vous guider dans votre parcours.",
    shortDescription: "Accès à un réseau de mentors expérimentés.",
    category: "Bridge Next-Gen",
    relevantFor: ["nextgen", "study", "business", "employment"],
  },
  {
    id: "orientation-financement-nextgen",
    title: "Orientation financement",
    description: "Aide à trouver des opportunités de financement pour vos études ou projets.",
    shortDescription: "Aide pour trouver des opportunités de financement.",
    category: "Bridge Next-Gen",
    relevantFor: ["nextgen", "study", "business"],
  },
  {
    id: "programme-complet-nextgen",
    title: "Programme complet NextGen",
    description: "Parcours structuré pour insertion professionnelle et entrepreneuriale.",
    shortDescription: "Parcours pour insertion professionnelle.",
    category: "Bridge Next-Gen",
    relevantFor: ["nextgen", "business", "employment"],
  },
  {
    id: "orientation-etudes",
    title: "Orientation études",
    description: "Conseil et accompagnement pour choisir votre parcours académique.",
    shortDescription: "Conseil pour choisir votre parcours académique.",
    category: "Bridge Next-Gen",
    relevantFor: ["nextgen", "study"],
  },
  {
    id: "recherche-stage",
    title: "Recherche de stage",
    description: "Accompagnement dans la recherche et sécurisation d'opportunités de stage.",
    shortDescription: "Accompagnement pour trouver un stage.",
    category: "Bridge Next-Gen",
    relevantFor: ["nextgen", "employment", "study"],
  },
  {
    id: "cv-lettre-motivation",
    title: "CV & Lettre de motivation",
    description: "Optimisation de votre CV et lettres de motivation pour maximiser vos chances.",
    shortDescription: "Optimisation de votre CV et lettres.",
    category: "Bridge Next-Gen",
    relevantFor: ["nextgen", "employment"],
  },
  {
    id: "preparation-entretien",
    title: "Préparation entretien",
    description: "Coaching pour réussir vos entretiens d'embauche ou d'admission.",
    shortDescription: "Coaching pour réussir vos entretiens.",
    category: "Bridge Next-Gen",
    relevantFor: ["nextgen", "employment", "study"],
  },
  {
    id: "installation-retraite",
    title: "Installation retraite",
    description: "Accompagnement complet pour une installation sereine adaptée aux retraités.",
    shortDescription: "Installation sereine adaptée aux retraités.",
    category: "Bridge Renaissance (Retraite)",
    relevantFor: ["retraite"],
  },
  {
    id: "accompagnement-sante-senior",
    title: "Accompagnement santé senior",
    description: "Coordination des besoins médicaux et suivi santé adapté aux seniors.",
    shortDescription: "Coordination des besoins médicaux seniors.",
    category: "Bridge Renaissance (Retraite)",
    relevantFor: ["retraite"],
  },
  {
    id: "suivi-mensuel-retraite",
    title: "Suivi mensuel retraité",
    description: "Assistance continue adaptée au rythme de vie des retraités.",
    shortDescription: "Assistance continue pour retraités.",
    category: "Bridge Renaissance (Retraite)",
    relevantFor: ["retraite"],
  },
  {
    id: "orientation-medicale",
    title: "Orientation médicale",
    description: "Mise en relation avec des structures de santé fiables et adaptées.",
    shortDescription: "Mise en relation avec des structures de santé.",
    category: "Santé & Assistance",
    relevantFor: ["installation", "investissement", "expat", "retraite"],
  },
  {
    id: "suivi-sante-mensuel",
    title: "Suivi santé mensuel",
    description: "Suivi régulier pour assurer votre bien-être et votre sécurité sanitaire.",
    shortDescription: "Suivi régulier de votre bien-être.",
    category: "Santé & Assistance",
    relevantFor: ["installation", "expat", "retraite"],
  },
];

export const servicePacks: ServicePack[] = [
  {
    id: "pack-essentiel",
    name: "Pack Essentiel",
    price: "150$",
    category: "Arrivée & Mobilité",
    description: "L'essentiel pour un premier contact serein avec le Congo",
    services: ["accueil-simple", "chauffeur-simple"],
    valueProposition: "Arrivée sécurisée et sans stress dès l'aéroport",
    relevantFor: ["court-sejour", "exploration"],
  },
  {
    id: "pack-confort",
    name: "Pack Confort",
    price: "250$",
    category: "Arrivée & Mobilité",
    description: "Confort et accompagnement pour vos premiers jours",
    services: ["chauffeur-ar", "assistance-48h"],
    valueProposition: "48h d'accompagnement pour éviter les erreurs courantes",
    relevantFor: ["court-sejour", "installation"],
  },
  {
    id: "pack-vip",
    name: "Pack VIP",
    price: "1000$",
    category: "Arrivée & Mobilité",
    description: "Expérience premium pour un séjour d'exception",
    services: ["accueil-vip", "chauffeur-journee", "organisation-sejour"],
    valueProposition: "Service haut de gamme avec coordination complète",
    relevantFor: ["investissement"],
  },
  {
    id: "pack-installation-serenite",
    name: "Pack Installation Sérénité",
    price: "1500$",
    category: "Installation",
    description: "Installation complète et sécurisée en 30 jours",
    services: [
      "accueil-simple",
      "recherche-logement",
      "mise-service-utilites",
      "ouverture-compte",
      "orientation-medicale",
    ],
    valueProposition: "Tout pour s'installer sereinement avec suivi 30 jours",
    relevantFor: ["installation"],
  },
  {
    id: "pack-expat-complet",
    name: "Pack Expat Complet",
    price: "2500$",
    category: "Installation",
    description: "Solution complète pour expatriés exigeants",
    services: [
      "assistance-complete",
      "recherche-logement",
      "installation-premium",
      "ouverture-compte",
      "orientation-terrain",
    ],
    valueProposition: "Installation premium avec suivi 3 mois",
    relevantFor: ["installation", "investissement", "expat"],
  },
  {
    id: "pack-investisseur",
    name: "Pack Investisseur",
    price: "5000$",
    category: "Business",
    description: "Accompagnement stratégique pour investisseurs",
    services: [
      "etude-faisabilite",
      "creation-entreprise-complete",
      "ouverture-compte",
      "mise-relation-partenaires",
      "accompagnement-strategique",
    ],
    valueProposition: "Stratégie complète avec suivi 6 mois",
    relevantFor: ["investissement"],
  },
  {
    id: "bridge-access",
    name: "Bridge Access",
    price: "299$/mois",
    category: "Abonnement",
    description: "Accès prioritaire et assistance continue",
    services: ["assistance-48h", "orientation-terrain", "ouverture-compte"],
    valueProposition: "Pour clients voyageant plus de 5 fois par an",
    relevantFor: ["court-sejour", "installation", "investissement"],
  },
  {
    id: "pack-nextgen-starter",
    name: "Pack NextGen Starter",
    price: "200$",
    category: "NextGen",
    description: "Démarrage idéal pour jeunes professionnels",
    services: [
      "coaching-individuel-nextgen",
      "cv-lettre-motivation",
      "preparation-entretien",
    ],
    valueProposition: "Optimisez votre profil et préparez-vous au marché",
    relevantFor: ["nextgen", "employment"],
  },
  {
    id: "pack-nextgen-etudiant",
    name: "Pack NextGen Étudiant",
    price: "250$",
    category: "NextGen",
    description: "Accompagnement complet pour étudiants",
    services: [
      "orientation-etudes",
      "orientation-financement-nextgen",
      "recherche-stage",
    ],
    valueProposition: "Structurez votre parcours académique et professionnel",
    relevantFor: ["nextgen", "study"],
  },
  {
    id: "pack-nextgen-entrepreneur",
    name: "Pack NextGen Entrepreneur",
    price: "800$",
    category: "NextGen",
    description: "Lancement de projet pour jeunes entrepreneurs",
    services: [
      "programme-mentorat-nextgen",
      "orientation-financement-nextgen",
      "diagnostic-projet",
      "mise-relation-partenaires",
    ],
    valueProposition: "Transformez votre idée en business viable",
    relevantFor: ["nextgen", "business"],
  },
  {
    id: "pack-nextgen-premium",
    name: "Pack NextGen Premium",
    price: "1200$",
    category: "NextGen",
    description: "Accompagnement complet sur 6 mois",
    services: [
      "programme-complet-nextgen",
      "programme-mentorat-nextgen",
      "orientation-financement-nextgen",
      "coaching-individuel-nextgen",
    ],
    valueProposition: "Programme intensif pour réussir votre insertion",
    relevantFor: ["nextgen", "business", "employment"],
  },
  {
    id: "pack-retraite-essentiel",
    name: "Pack Retraite Essentiel",
    price: "800$",
    category: "Retraite",
    description: "L'essentiel pour une arrivée sereine",
    services: [
      "accueil-simple",
      "chauffeur-simple",
      "recherche-logement",
      "orientation-medicale",
    ],
    valueProposition: "Installation de base avec orientation santé",
    relevantFor: ["retraite"],
  },
  {
    id: "pack-retraite-confort",
    name: "Pack Retraite Confort",
    price: "1800$",
    category: "Retraite",
    description: "Installation complète et sécurisée",
    services: [
      "assistance-complete",
      "recherche-logement",
      "mise-service-utilites",
      "ouverture-compte",
      "accompagnement-sante-senior",
      "installation-retraite",
    ],
    valueProposition: "Installation complète avec suivi santé senior",
    relevantFor: ["retraite"],
  },
  {
    id: "pack-retraite-serenite",
    name: "Pack Retraite Sérénité",
    price: "2500$",
    category: "Retraite",
    description: "Accompagnement premium pour retraités",
    services: [
      "assistance-complete",
      "recherche-logement",
      "installation-premium",
      "ouverture-compte",
      "accompagnement-sante-senior",
      "suivi-mensuel-retraite",
    ],
    valueProposition: "Installation premium avec suivi mensuel continu",
    relevantFor: ["retraite"],
  },
];
